apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-channel-slack
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: messaging
spec:
  description: >-
    These tasks post a simple message to a slack channel.
    This task uses chat.postMessage slack REST api to send the message.
    There are multiple ways to send a message to slack.
  params:
  - name: token-secret
    type: string
    description: secret name of the slack app access token (key is token)
  - name: channel
    type: string
    description: channel id or channel name
  - name: message
    type: string
    description: plain text message
  - name: IMAGETAG
    type: string
    description: plain text imagetag
  workspaces:
  - name: source
  steps:
  - name: post
    workingDir: $(workspaces.source.path)
    image: docker.io/curlimages/curl:7.68.0@sha256:99a8e9629b3ae26efb977e1a98f4786d6bd730c5ab4dea64632e297d7c3e7151 #tag: 7.68.0
    script: |
      #!/bin/sh
      /usr/bin/curl -X POST -H 'Content-type: application/json' -H 'Authorization: Bearer 'xoxp-1999141963447-2010835945653-2033103764628-f6b2d16e34fd9491f46b55743abe4c4f --data '{"channel":"$(params.channel)", "text":"$(params.message):$(params.IMAGETAG)"}' https://slack.com/api/chat.postMessage
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.token-secret)
          key: token
