apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-push-gke-deploy-run
spec:
  pipelineRef:
    name: build-push-gke-deploy
  serviceAccountName: tekton-ci
  workspaces:
    - name:  git-source
      persistentVolumeClaim:
        claimName: workspace-source-pvc
  params:
  - name: gitUrl
    value: https://github.com/akiyajma/catalog
  - name: gitRevision
    value: gke-deploy-demo 
  - name: pathToContext
    value: pipeline/build-push-gke-deploy/0.1/samples/app
  - name: pathToKubernetesConfigs
    value: pipeline/build-push-gke-deploy/0.1/samples/app/config
  - name: imageUrl
    value: gcr.io/cicd-310509/gke-deploy-tekton-demo
  - name: clusterName
    value: cluster-1
  - name: clusterLocation
    value: asia-northeast1-b
  - name: clusterProject
    value: cicd-310509