---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push-gke-deploy
  labels:
    app.kubernetes.io/version: '0.1'
  annotations:
    tekton.dev/pipelines.minVersion: '0.12.1'
    tekton.dev/tags: build, push, deploy
spec:
  description: >-
    This Pipeline builds, pushes, and deploys your application to a Google Kubernetes
    Engine cluster using gke-deploy.
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: master
    - name: pathToContext
      type: string
      description: The path to the build context relative to your source repo's root. This is used by Kaniko.
      default: .
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build, relative to the context.
      default: Dockerfile
    - name: pathToKubernetesConfigs
      type: string
      description: The path to the Kubernetes configs to deploy, relative to your source repo's root.
    - name: imageUrl
      type: string
      description: URL of image repository.
    - name: clusterName
      type: string
      description: Name of target GKE cluster to deploy to.
    - name: clusterLocation
      type: string
      description: Zone/region of target GKE cluster to deploy to.
    - name: clusterProject
      type: string
      description: Project of target GKE cluster to deploy to.
      default: ''
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: imagetag
      taskRef:
        name: imagetag
      runAfter:
        - clone-repo
      workspaces:
        - name: imagetag
          workspace: git-source
    - name: kaniko
      taskRef:
        name: kaniko
      runAfter:
        - imagetag
      params:
        - name: CONTEXT
          value: '$(params.pathToContext)'
        - name: IMAGE
          value: '$(params.imageUrl)'
        - name: IMAGETAG
          value: "$(tasks.imagetag.results.IMAGE-TAG)"
      workspaces:
        - name: source
          workspace: git-source
  finally:
    - name: slack-failed
      taskRef: 
        name: send-to-channel-slack
      workspaces:
        - name: source
          workspace: git-source
      when:
        - input: "$(tasks.kaniko.status)"
          operator: in
          values: ["Failed"]
      params:
        - name: token-secret
          value: token-secret
        - name: channel
          value: "C020AQPPYR3"
        - name: message
          value: "Build Fail"
        - name: IMAGETAG
          value: "$(tasks.imagetag.results.IMAGE-TAG)"
    - name: slack-succeeded
      taskRef: 
        name: send-to-channel-slack
      workspaces:
        - name: source
          workspace: git-source
      when:
        - input: "$(tasks.kaniko.status)"
          operator: in
          values: ["Succeeded"]
      params:
        - name: token-secret
          value: token-secret
        - name: channel
          value: "C020AQPPYR3"
        - name: message
          value: "Build Success"
        - name: IMAGETAG
          value: "$(tasks.imagetag.results.IMAGE-TAG)" 